# Generated by Django 3.2.6 on 2022-01-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracter', models.CharField(max_length=2)),
                ('codigo', models.CharField(max_length=4)),
            ],
        ),
    ]
